# Generated by Django 6.1 on 2026-08-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
