# Generated by Django 6.1 on 2026-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_app", "0003_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
