# Generated by Django 6.1 on 2026-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_app", "0004_review_average_rating_review_number_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="average_rating",
        ),
        migrations.RemoveField(
            model_name="review",
            name="number_rating",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="average_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_rating",
            field=models.IntegerField(default=0),
        ),
    ]
